[build]
builder = "NIXPACKS"
buildCommand = "cd backend/EGTI && mvn clean package -DskipTests"

[deploy]
startCommand = "cd backend/EGTI && java -jar target/egti-0.0.1-SNAPSHOT.jar"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
